sonar.projectKey=ifs24005-pabwe2026-nextjs
sonar.projectName=ifs24005-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,.next/**,**/*.test.ts,**/*.test.tsx,src/test-utils.tsx,src/setupTests.ts,src/vitest.setup.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,src/test-utils.tsx
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx